apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ilyakhrenkov/todo_app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: PGHOST
          value: postgres
        - name: PGUSER
          value: postgres
        - name: PGDATABASE
          value: todos
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD